% PointToPointIncludes.m

addpath './CircuitModel'
addpath './CircuitElement'
addpath './CircuitElement/enums'
addpath './Circuits'
addpath './Circuits/AmpClippers'
addpath './Circuits/AmpToneStacks'
addpath './Circuits/AudioFilters'
addpath './Circuits/CircuitChains'
addpath './Circuits/ClassicFilters'
addpath './Circuits/ClippingCircuits'
addpath './Circuits/PedalClippers'
addpath './Circuits/PedalToneCircuits'
addpath './XML'