classdef LaneyLC15ToneStack < Circuit 
    
    methods
        function [o] = LaneyLC15ToneStack()
            
            o.layout.numNodes = 7;
            o.layout.Vin = VoltageInput(1,0);
            o.layout.Vout = VoltageOutput(3,0);
            
            R1 = Resistor(33e3,1,5);
            o.layout.Rs = [R1];
            
            C1 = Capacitor(470.0e-12,1,2);
            C2 = Capacitor(22.0e-9,5,4);
            C3 = Capacitor(22.0e-9,5,6);
            o.layout.Cs = [C1; C2; C3];
            
            Vr1 = VariableResistor(22e4,3,...
                VariableResistorDirection.INVPROPORTIONAL,...
                VariableResistorSkew.LINEAR,...
                2,3);
            Vr2 = VariableResistor(22e4,3,...
                VariableResistorDirection.PROPORTIONAL,...
                VariableResistorSkew.LINEAR,...
                3,4);
            Vr3 = VariableResistor(1e6,1,...
                VariableResistorDirection.PROPORTIONAL,...
                VariableResistorSkew.LINEAR,...
                4,7);
            Vr4 = VariableResistor(22e3,2,...
                VariableResistorDirection.INVPROPORTIONAL,...
                VariableResistorSkew.LINEAR,...
                7,6);
            Vr5 = VariableResistor(22e3,2,...
                VariableResistorDirection.PROPORTIONAL,...
                VariableResistorSkew.LINEAR,...
                6,0);
            
            o.layout.VarRs = [Vr1 ; Vr2; Vr3; Vr4; Vr5];
            
            o.circuit = CircuitModel(o.layout);

        end
    end
end

